apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-feign-image
spec:
  selector:
    matchLabels:
      app: k8-feign-image
  replicas: 1 
  template:
    metadata:
      labels:
        app: k8-feign-image
    spec:
      containers:
      - name: k8-feign-image
        image: gcr.io/demoreactive-264604/k8-feign-image
        ports:
        - containerPort: 8088
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 20
          periodSeconds: 20    
---
apiVersion: v1
kind: Service
metadata:
  name: k8-feign-image-service
  labels:
    name: k8-feign-image-service
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: k8-feign-image
  type: NodePort